import { OpenAPIDefinitions, RouteConfig } from '@node-openapi/fastify';

export const bearerSecurity: OpenAPIDefinitions = {
  type: 'component',
  componentType: 'securitySchemes',
  name: 'Token',
  component: {
    type: 'apiKey',
    in: 'header',
    name: 'Authorization',
    description:
      "For accessing the protected API resources, you must have received a valid JWT token after registering or logging in. This JWT token must then be used for all protected resources by passing it in via the 'Authorization' header.\n\nA JWT token is generated by the API by either registering via /users or logging in via /users/login.\n\nThe following format must be in the 'Authorization' header :\n\n    Token xxxxxx.yyyyyyy.zzzzzz\n    \n",
  },
};

export const defaultRouteSecurity = [
  {
    Token: [],
  },
] satisfies RouteConfig['security'];
